# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/post_protos.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import user_protos_pb2 as protos_dot_user__protos__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/post_protos.proto\x12\x05posts\x1a\x18protos/user_protos.proto\"<\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x19\n\x04user\x18\x03 \x01(\x0b\x32\x0b.users.User\"\x11\n\x0fGetPostsRequest\".\n\x10GetPostsResponse\x12\x1a\n\x05posts\x18\x01 \x03(\x0b\x32\x0b.posts.Post2D\n\x05Posts\x12;\n\x08GetPosts\x12\x16.posts.GetPostsRequest\x1a\x17.posts.GetPostsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.post_protos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POST']._serialized_start=61
  _globals['_POST']._serialized_end=121
  _globals['_GETPOSTSREQUEST']._serialized_start=123
  _globals['_GETPOSTSREQUEST']._serialized_end=140
  _globals['_GETPOSTSRESPONSE']._serialized_start=142
  _globals['_GETPOSTSRESPONSE']._serialized_end=188
  _globals['_POSTS']._serialized_start=190
  _globals['_POSTS']._serialized_end=258
# @@protoc_insertion_point(module_scope)
