# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/user_protos.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18protos/user_protos.proto\x12\x05users\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x91\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07surname\x18\x03 \x01(\t\x12.\n\nis_deleted\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"2\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\"\x11\n\x0fGetUsersRequest\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x12\x43reateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x10GetUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\"/\n\x12\x44\x65leteUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User2\xca\x01\n\x05Users\x12\x41\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\x12;\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\x12\x41\n\nDeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.user_protos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=101
  _globals['_USER']._serialized_end=246
  _globals['_CREATEUSERREQUEST']._serialized_start=248
  _globals['_CREATEUSERREQUEST']._serialized_end=298
  _globals['_GETUSERSREQUEST']._serialized_start=300
  _globals['_GETUSERSREQUEST']._serialized_end=317
  _globals['_DELETEUSERREQUEST']._serialized_start=319
  _globals['_DELETEUSERREQUEST']._serialized_end=350
  _globals['_CREATEUSERRESPONSE']._serialized_start=352
  _globals['_CREATEUSERRESPONSE']._serialized_end=399
  _globals['_GETUSERSRESPONSE']._serialized_start=401
  _globals['_GETUSERSRESPONSE']._serialized_end=447
  _globals['_DELETEUSERRESPONSE']._serialized_start=449
  _globals['_DELETEUSERRESPONSE']._serialized_end=496
  _globals['_USERS']._serialized_start=499
  _globals['_USERS']._serialized_end=701
# @@protoc_insertion_point(module_scope)
